### ISSUE TITLE
Always "User not found"

### ISSUE THREAD

**Issue by arielherself** [RedHeadphone/codeforces-readme-stats#14]
Everyone's card is getting 404 response with message "user not found". [example](https://codeforces-readme-stats.vercel.app/api/card?username=tourist)

**Comment by arielherself** [comment]
This is also mentioned in #8, and I think it's probably caused by a Cloudflare CAPTCHA page. Codeforces used to turn it on only during contests, but now it's used more frequently.

**Comment by RedHeadphone** [comment]
Logging error, to find the exact issue https://github.com/RedHeadphone/codeforces-readme-stats/commit/48ccf501186fb1b6dd1f6dd74fcaf696ef00745b 

If it is an issue from codeforces side, I am working on a cache adaptor that will show the last stats (before codeforces API went down) in #6 

If you are using the API in github readme profile, I suggest having a script and github action cron that update the stats card https://github.com/RedHeadphone/RedHeadphone

**Comment by RedHeadphone** [comment]
> Error: Request failed with status code 403

Tried changing the region of my vercel function, but still the same response. 

So, it is most likely an issue from codeforces server, I can change the user-agent when calling their API but I don't think that will fix it.

The most suitable action, for now, would be to wait for codeforces server to fix it.
