### ISSUE TITLE
Make Codeforces rank color look good in both light and dark mode

### ISSUE THREAD

**Issue by RedHeadphone** [RedHeadphone/codeforces-readme-stats#2]
Make Codeforces rank color look good in both light and dark mode .Hex code for each rank can be found [here](https://github.com/RedHeadphone/Codeforces-readme-stats/blob/master/src/common.js)

**Comment by siddarthpai** [comment]
hey! can i work on this

**Comment by RedHeadphone** [comment]
@siddarthpai yeah, you can work on it! Do attach the screenshots of how each rank text looks in both light mode and dark mode in the PR.
