### ISSUE TITLE
SVG fix for safari browser

### ISSUE THREAD

**Issue by RedHeadphone** [RedHeadphone/codeforces-readme-stats#3]
Stats card in safari browser:
![image](https://user-images.githubusercontent.com/55500003/226682307-563e9d37-77d9-4b70-a102-99f5ccb0b33c.png)

Possible [fix](https://stackoverflow.com/questions/61272308/why-does-webkit-safari-ios-macos-render-my-svg-transformations-in-a-different)

**Comment by ochowei** [comment]
I'm interesting in this issue, can i pickup this one?

**Comment by RedHeadphone** [comment]
@ochowei sure

**Comment by RedHeadphone** [comment]
Because this issue must be resolved as soon as possible, I am keeping it open to everyone.
