### ISSUE TITLE
Badge fails to load, API response says "user not found" even on valid users

### ISSUE THREAD

**Issue by Nis-Han** [RedHeadphone/codeforces-readme-stats#8]
Most probably, there is some change in the CF API that might be causing this issue.

**Comment by Nis-Han** [comment]
Somehow its back to working, without any new commit/update.
Maybe it was a CF side issue

**Comment by RedHeadphone** [comment]
The same API response was observed today. This is related to #6, when contest or system testing is going on codeforces, their API acts differently resulting in common error response ([line](https://github.com/RedHeadphone/codeforces-readme-stats/blob/master/src/pages/api/card.js#L194)). A temporary fix for this could be storing the last valid (200 status or smth like that) responses from the codeforces server, and using that data when codeforces API is not working as expected. Also, there is a need for a logging setup.
